configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - ".moban.d"
  configuration: libxlsxwpy.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
  - .travis.yml: travis.yml
  - LICENSE: LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - test.sh: test.sh.jj2
  - test.bat: test.sh.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
